apiVersion: v1
kind: Service

metadata:
  name: mongodb
  namespace: roboshop

spec:
  type: ClusterIP

  selector:
    name: roboshop
    env: {{ .Values.service.env }}
    running: mongodb

  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017