manifest:
  imageDocrepo: balaji1729/user
  imageVersion: v1
  cpulimit: 300m
  memorylimit: 256Mi
  env: dev
service:
  env: dev
autoscaling:
  minReplicas: 1
  maxReplicas: 10
  averageUtilization: 50
  env: dev