apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: roboshop
    env: {{.Values.manifest.env}}
    running: catalogue
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: roboshop
      env: {{.Values.manifest.env}}
      running: catalogue
  template:
    metadata:
      labels:
        name: roboshop
        env: {{.Values.manifest.env}}
        running: catalogue
    spec:
      containers:
      - name: catalogue
        image: {{.Values.manifest.imageDocrepo}}:{{.Values.manifest.imageVersion}}
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: {{.Values.manifest.cpulimit}}
            memory: {{.Values.manifest.memorylimit}}
        envFrom:
        - configMapRef:
            name: catalogue
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 30 