apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
      name: roboshop
      env: {{.Values.service.env}}
      running: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080